### ISSUE TITLE
Configuration for running the code

### ISSUE THREAD

**Issue by DanielAndreasen** [BrownDwarf/gollum#105]
Hi all,

It's a very nice tool you have put together here, and I wish it was available when I did my PhD.

I think the paths for the libraries we have to download should be in a configuration file, rather than hardcoded into the software itself (it can default to what you have now though: `~/libraries`).
But if you have a file like `~/.config/gollum/config.yml` (or whichever format you prefer), where the path to the libraries can be set, and possible other settings as well, I think it would be very nice.

Review link: https://github.com/openjournals/joss-reviews/issues/6601

Sorry for the late review, but more will come soon as I'm getting into testing.

**Comment by Sujay-Shankar** [comment]
Hi Daniel:

Thanks for your feedback! You are absolutely right that a configuration file is the way to go, and while the main gollum library doesn't have it yet, we're in the process of writing up a V2 interface that uses I believe .env files to house path data for grids. 
I'll get working on implementing a similar thing for the original interface, and have it point to the same directory.

**Comment by Sujay-Shankar** [comment]
Updates: With the last two commits, this issue should be solved. I've made PHOENIX, Sonora, and coolTLUSTY classes now default to pulling their path from config.env, located in gollum's source directory. The actual values are the same as before. The setup files have also been updated to reflect the new dependency of python-dotenv. Please let me know if there's anything else that comes up pertaining to this issue, if not we should be able to safely close this one.

**Comment by DanielAndreasen** [comment]
Great work. The only thing a bit annoying might be that changing the config, means the repository is out of sync, which can lead to problems when doing `git pull`, but I can live with that. Alternatively you could just write in the `README.md` how to write the config file, and have it in `.gitignore`, but this is also fine. Up to you if you will change it, or just close the issue.

**Comment by Sujay-Shankar** [comment]
Thanks for pointing that out, you're definitely right. I'll go with a 'constant' template config file, and create some mechanism to automatically copy the template to a git untracked config.env if it doesn't exist, and not overwrite existing config otherwise. I'll close the issue once I push this change.

**Comment by Sujay-Shankar** [comment]
Closed by c8a630
