### ISSUE TITLE
Gollum + Muler environment file and dual installation instructions.

### ISSUE THREAD

**Issue by gmace** [BrownDwarf/gollum#11]
Currently we make two environments, one for Muler and another for Gollum. We then must switch environments to switch tools. 

A single environment file for both packages would make the two more compatible. 

Installation instructions for the merged environment should be provided in the documents. 

It seems like gollum is an extension to muler, and so making the muler documentation include the the gollum setup, that would be helpful.

**Comment by gully** [comment]
Thank you for pointing out this inconsistency in the documentation across the two packages.  We expect that the need to use both muler and gollum in the same conda environment will be common, maybe even the predominant use case.  I have made the conda environments between muler and gollum identical, and introduced the following remedy in the [installation documentation](https://gollum-astro.readthedocs.io/en/latest/install.html):

We added a description for how to install gollum into an existing muler environment.  I did not make the same remedy in the muler documentation.  In the future we may bifurcate the developer instructions and user instructions, with the primary recommendation to be pip install, in which case the need for a sandboxed conda environment is lessened.  

Thank you again for helping to get the packages more streamlined through this issue report! 🚀
