### ISSUE TITLE
Docs make presumption about download directory

### ISSUE THREAD

**Issue by rhdtownsend** [BrownDwarf/gollum#111]
A number of places in the docs presume that the download directory will be ~/Downloads (see, e.g., the instructions [here](https://gollum-astro.readthedocs.io/en/latest/fetching_models.html). While that may be true on MacOS, it certainly isn't part of the [Linux FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). Suggest making the docs more download-agnostic. For instance, in the case of the Phoenix download instructions, why not have the user directly download into their chosen spectral library directory, rather than to ~/Downloads?

Review link: https://github.com/openjournals/joss-reviews/issues/6601

**Comment by Sujay-Shankar** [comment]
I've pushed changes that make the documentation more download-agnostic. To your latter point, with PHOENIX, users are required to mess with the native directory structure to get it to how gollum likes it, so I think having users download to an intermediate location and then populate the final location with the correct structure is less prone to things overwriting themselves and breaking. If the current state is satisfactory, let me know and we can close this issue. Thanks for pointing this out!
