### ISSUE TITLE
Comparison against MSG

### ISSUE THREAD

**Issue by rhdtownsend** [BrownDwarf/gollum#112]
It would be helpful for the documentation to compare gollum's capabilities against those of [MSG](https://github.com/rhdtownsend/msg) (full disclosure, I'm the developer of MSG). From what I can see, gollum does not support any kind of interpolation in grids (MSG does). Is this a design choice, made under the expectation that higher-level modules will provide interpolation functionality? If so, it would be helpful having that narrative in the introductory documentation, so users can quickly assess whether gollum is the right fit (pardon the pun!) for them.

Review link: https://github.com/openjournals/joss-reviews/issues/6601

**Comment by Sujay-Shankar** [comment]
That's true, we should mention up front that we don't currently support grid interpolation. It's a future plan to implement into gollum, just not one of our goals for gollum in its current iteration. I put a bit on the homepage specifying this so users don't get the wrong idea.
