### ISSUE TITLE
API documents need cleaning up

### ISSUE THREAD

**Issue by rhdtownsend** [BrownDwarf/gollum#113]
The API docs have seen quite a bit of improvement since I began reviewing gollum, but still need some tidying up. For instance, there is a bogus "PHOENIX Spectrum" header at the top of the class list.

Review link: https://github.com/openjournals/joss-reviews/issues/6601

**Comment by Sujay-Shankar** [comment]
The most recent commits should have fixed the extra headers appearing in the documentation pages, instead replaced by module-specific headers for PHOENIX, Sonora, etc. Are there any other issues that stand out in the documentation?
