### ISSUE TITLE
Demo of the PHOENIX Interactive Dashboard for Stellar Spectra

### ISSUE THREAD

**Issue by DanielAndreasen** [BrownDwarf/gollum#116]
Are you able to run this tutorial? I get this error:
`Exception: Neither .variance.fits or .sn.fits exists in the same path as the spectrum file to get the uncertainity.  Please provide one of these files in the same directory as your spectrum file.`

This is in the `muler` package, so I'm not really able to debug it much further as is.

**Comment by Sujay-Shankar** [comment]
I've updated the demo to use local data files instead of online ones, it should no longer throw this error.
