### ISSUE TITLE
Guidelines for contribution and statement of need

### ISSUE THREAD

**Issue by DanielAndreasen** [BrownDwarf/gollum#119]
I'm just about done with the checklist before I can recommend this for publication.

Two things missing from that checklist are:
* Guidelines for contribution. Simply add in the readme how to contribute, either to the code (pull request), or with questions (open an issue).
* Statement of need. This is more or less written in the paper, but can you add a section with that title? I.e. what is the need of this tool (already written; for education and explorative research basically).

https://github.com/openjournals/joss-reviews/issues/6601

**Comment by Sujay-Shankar** [comment]
Thanks for the feedback Daniel!
We already had the contribution instructions in the readme, and the Statement of Need section was in the paper, but I suspect you meant that they should be more explicit.
I've updated both to incorporate both of your points, the readme is more exhaustive in its contribution instructions and the statement of need section now explicitly states that gollum is targeted towards education and explorative research.
Let me know if the changes in the recent commit are satisfactory, and we should be good to go ahead and close this one up.

**Comment by DanielAndreasen** [comment]
Beautiful. I think I might just have overlooked some things during my first review of the readme/paper. But it reads better now I think.
