### ISSUE TITLE
Documentation or utility function for fetching the raw model grids

### ISSUE THREAD

**Issue by gully** [BrownDwarf/gollum#17]
We should add documentation, scripts, or a utility function for automatically fetching the model grids.  The automatic fetching is tricky because we can't assume everyone has, say, `wget` or whatever.  We might want to use `beautifulsoup` (or more likely `requests`) to make the requests: that's another dependency to add in---which is OK but adds some complexity.  

The other hiccup is that the grids are huge, so we wouldn't want to just cram them into a hidden folder, and we'd want to make sure the user knows how big they will be in advance.

**Comment by gully** [comment]
Here is the link to the high-res PHOENIX models:

ftp://phoenix.astro.physik.uni-goettingen.de/HiResFITS/

**Comment by nattieg** [comment]
Note for later documentation: if using the ftp link above, the default path assumed by `gollum` of  `~/libraries/raw/PHOENIX/` must point to the contents within the `HiResFITS/PHOENIX-ACES-AGSS-COND-2011/` directory. In other words, the PHOENIX path should point to a directory that contains the metallicity directories, NOT the `HiResFITS` directory alone. It also assumes the default path directory includes the wavelength file `WAVE_PHOENIX-ACES-AGSS-COND-2011.fits`. This requires copying the wavelength file from its original location in `HiResFITS/`to be in the local equivalent of `HiResFITS/PHOENIX-ACES-AGSS-COND-2011/`

**Comment by gully** [comment]
Hooray!  We have a new documentation page for fetching the models and mimicking the directory structure.  These should be considered "guides" at the moment because not-all-OS'es will have wget, and the versions of some of the bash commands may be platform specific.

https://gollum-astro.readthedocs.io/en/latest/fetching_models.html

We could aspire to make a standalone script that automatically fetches the models and creates the directory structure.  Happy to work on that with folks who are interested!

Thank you to @gmace and @nattieg for requesting this valuable documentation, and providing some guidance towards it.
