### ISSUE TITLE
Split PHOENIX and Sonora tests

### ISSUE THREAD

**Issue by nattieg** [BrownDwarf/gollum#20]
Many users, especially students, are likely to only be interested in loading either PHOENIX or Sonora models, not both. Recommend providing something like `py_phoenix.test` and `py_sonora.test` so student users aren't bogged down with failures related to grids they are not currently interested in.

**Comment by gully** [comment]
Thank you for filling the issue! That's a good point, most folks will only want either Sonora or Phoenix, but not both.  I've updated the [installation documentation](https://gollum-astro.readthedocs.io/en/latest/install.html) to reflect the way to run each test separately.  Good recommendation, thank you!
