### ISSUE TITLE
Make an animated gif showing how the dashboard works

### ISSUE THREAD

**Issue by gully** [BrownDwarf/gollum#25]
Currently the dashboard only works locally, meaning that it cannot easily be uploaded to an html website and used in the browser in real-time.  Instead, let's make an animated gif from a short screen recording.  We can then upload that animated gif to social media for advertising purposes and we can display it instead the tutorial.

**Comment by Jiayi-Cao** [comment]
![gollum_dashboard_demo](https://user-images.githubusercontent.com/98151293/167173097-31427d83-f7fc-4146-a520-34e6b97b3b1b.gif)
