### ISSUE TITLE
A function for finding the closest grid point in a lattice (3 dimensional space)

### ISSUE THREAD

**Issue by Jiayi-Cao** [BrownDwarf/gollum#34]
The sonora.py code currently takes in effective temperature, surface gravity, and metallicity as grid points in a three dimensional space. However, the points are in a jagged array (#31 ), so we need to create a function to find the nearest grid point whenever a grid point that doesn't exist is found.

**Comment by gully** [comment]
In discussion with @Jiayi-Cao today, we agreed it would be useful to test this function.  Originally in a Jupyter notebook, but possibly in a standalone unit test.
