### ISSUE TITLE
Make sure we are using deep copies instead of self?

### ISSUE THREAD

**Issue by gully** [BrownDwarf/gollum#43]
We learned a few lessons from `muler` that we should incorporate into gollum.  We had to make deep copies instead of `self` in order to avoid in-place operations.  We should do the same here.  It has not appeared to cause a problem yet, but it might eventually.

**Comment by SujayShankarUT** [comment]
After parsing through the gollum code for a bit, it looks like the coast is clear in terms of us doing any accidental in-place operations. We should be good to close this.
